// Type-level counterpart of exports.test.ts: every type arc42-language and
// biz42 import from @cli42/lib. `vp check` fails when one is removed or
// renamed. Nothing here runs.
import type {
  DiagramChange,
  ChangeStatus,
  ConsistencyFinding,
  DiffDocument,
  DiffOptions,
  DiffSegment,
  DiffView,
  DocumentChangeSummary,
  EdgeChange,
  ElementChange,
  Location,
  OutlineEntry,
  ProseSectionChange,
  SectionContent,
  SectionRef,
  WorkspaceDiff,
  AttributeChange,
} from "@cli42/lib/diff";
import type {
  ExplainCrossRefResult,
  ExplainFieldResult,
  ExplainIgnoreResult,
} from "@cli42/lib/explain";
import type {
  CommitFiles,
  DiffSpec,
  DocumentCommit,
  DocumentHistory,
  SnapshotSource,
} from "@cli42/lib/git";
import type {
  MermaidGrammar,
  MermaidParseFailure,
  MermaidParseRequest,
  MermaidParseResult,
  MermaidParseSuccess,
  MermaidSyntaxParser,
  MermaidSyntaxTarget,
} from "@cli42/lib/mermaid";
import type {
  DiagramResult,
  ElementOf,
  MetaRelation,
  ParseError,
  ParseWarning,
  SourceLocation,
} from "@cli42/lib/model";
import type { NotationAdapter, Parser, ProseRenderer } from "@cli42/lib/notation";
import type {
  BareMermaidNode,
  DiagramMetadata,
  DslDialect,
  HeadingNode,
  IgnoreNode,
  MarkdownBlockNode,
  ProseNode,
} from "@cli42/lib/parser";
import type { CrossRefMeta, FieldMeta } from "@cli42/lib/schema";
import type {
  Diagnostic,
  IgnoreDirective,
  Rule,
  RuleDocs,
  RuleMeta,
  RuleType,
  Severity,
} from "@cli42/lib/validator";
import type { z } from "@cli42/lib/schema";

export type ConsumedTypes = [
  AttributeChange,
  ChangeStatus,
  ConsistencyFinding,
  DiagramChange,
  DiffDocument,
  DiffOptions,
  DiffSegment,
  DiffView,
  DocumentChangeSummary,
  EdgeChange,
  ElementChange,
  Location,
  OutlineEntry,
  ProseSectionChange,
  SectionContent,
  SectionRef,
  WorkspaceDiff,
  ExplainCrossRefResult,
  ExplainFieldResult,
  ExplainIgnoreResult,
  CommitFiles,
  DiffSpec,
  DocumentCommit,
  DocumentHistory,
  SnapshotSource,
  MermaidGrammar,
  MermaidParseFailure,
  MermaidParseRequest,
  MermaidParseResult,
  MermaidParseSuccess,
  MermaidSyntaxParser,
  MermaidSyntaxTarget<"flowchart">,
  DiagramResult<unknown>,
  ElementOf<{ block: z.ZodObject<{ id: z.ZodString }> }>,
  MetaRelation,
  ParseError,
  ParseWarning,
  SourceLocation,
  NotationAdapter<"markdown", unknown>,
  Parser<unknown>,
  ProseRenderer,
  BareMermaidNode,
  DiagramMetadata,
  DslDialect<unknown, "inFence">,
  HeadingNode,
  IgnoreNode,
  MarkdownBlockNode,
  ProseNode,
  CrossRefMeta,
  FieldMeta,
  Diagnostic,
  IgnoreDirective,
  Rule<unknown, unknown>,
  RuleDocs,
  RuleMeta,
  RuleType,
  Severity,
];
